services:
  web-text-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - BROWSERLESS_WS_ENDPOINT=
      - BROWSERLESS_URL=
      - ALLOW_LOCAL_LAUNCH=true
      - USER_AGENT=
      - ACCEPT_LANGUAGE=
      - TIMEZONE=
      - VIEWPORT_WIDTH=
      - VIEWPORT_HEIGHT=
      - DEVICE_SCALE_FACTOR=
      - HEADLESS=
      - CHROME_EXECUTABLE_PATH=
      - USER_DATA_DIR=

  web-text-proxy-browserless:
    profiles: ["browserless"]
    build:
      context: .
      dockerfile: Dockerfile.browserless
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - BROWSERLESS_WS_ENDPOINT=
      - BROWSERLESS_URL=
      - ALLOW_LOCAL_LAUNCH=false
      - USER_AGENT=
      - ACCEPT_LANGUAGE=
      - TIMEZONE=
      - VIEWPORT_WIDTH=
      - VIEWPORT_HEIGHT=
      - DEVICE_SCALE_FACTOR=
      - HEADLESS=
      - CHROME_EXECUTABLE_PATH=
      - USER_DATA_DIR=
