services:
  web-text-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  web-text-proxy-browserless:
    profiles: ["browserless"]
    build:
      context: .
      dockerfile: Dockerfile.browserless
    ports:
      - "3000:3000"
    environment:
      - BROWSERLESS_WS_ENDPOINT
      - BROWSERLESS_URL
