services:
  text:
    build: .
    ports:
      - 3789:3000
    environment:
      - PORT=3000
      - BROWSERLESS_WS_ENDPOINT=ws://10.10.10.10:4000
      - BROWSERLESS_URL=
      - ALLOW_LOCAL_LAUNCH=false
      - USER_AGENT=
      - ACCEPT_LANGUAGE=
      - TIMEZONE=
      - VIEWPORT_WIDTH=
      - VIEWPORT_HEIGHT=
      - DEVICE_SCALE_FACTOR=
      - HEADLESS=
      - CHROME_EXECUTABLE_PATH=
      - USER_DATA_DIR=
